### ISSUE TITLE
SMF 2.1 RC2 ошибка.

### ISSUE THREAD

**Issue by satsis** [dragomano/Zen-Block#3]
Ставит без ошибок.
В админке не появляется ничего кроме ошибок в логе.

Тип ошибки: Общие  							 							Вызов хука: функция "ZenBlock::hooks" в файле /home/www/sat/Sources/Class-ZenBlock.php не может быть вызвана. 							 							https://test/index.php?action=admin;area=logs;sa=errorlog;desc |  
-- | --
Гость 							 							Сегодня в 23:48:40 						 						 							 							Тип ошибки: Общие  							 							Вызов хука: не удалось загрузить файл /home/www/sat/Sources/$sourcedir/Class-ZenBlock.php. 							 							https://test/index.php?action=admin;area=logs;sa=errorlog;desc

**Comment by dragomano** [comment]
Название файла с модом, где скачали?
Параметры сервера?
Опишите процесс установки.

**Comment by satsis** [comment]
Скачал тут https://custom.simplemachines.org/mods/index.php?mod=4229
Сервер Centos 6, httpd 2.4 php-fpm 7.3
SMF 2.1 RC2
Другие модули ставит просто или в режиме эмляции
Ваши ставит без ошибок, но при удалении файлы не найдены

BBC Message Boxes | 3.0 | Вчера в 23:09:40 | Удаление 
2 | Downloads System | 3.0.5 | Вчера в 22:15:46 | Удаление в режиме эмуляции: 
3 | Legacy Karma | 1.0.1 | Вчера в 22:47:27 | Удаление в режиме эмуляции: 
4 | Avatars Display Integration | 1.2 | Вчера в 23:05:09 | Удаление 
5 | TopicStarter | 1.8.1 | Вчера в 22:55:18 | Удаление 
6 | FA Board Icons | 1.2.1 | Вчера в 23:06:50 | Удаление 
7 | Quick Spoiler | 1.2.6 | нет данных | Установка мода 									
8 | dQuote Selection and Notification | 2.7.2 | Вчера в 22:56:20 | Удаление в режиме 
9 | EhPortal | 1.24 | Вчера в 22:10:31 | Удаление 
10 | Karma | 1.0 | Вчера в 22:45:21 | Удаление в режиме
11 | Forum Width Setting | 1.1 | Вчера в 22:09:31 | Удаление

**Comment by satsis** [comment]
Не смог ни один ваш модуль поставить
Similar-Topics
Quick Spoiler

**Comment by dragomano** [comment]
Интересно, почему вызывается файл по адресу /home/www/sat/Sources/$sourcedir/Class-ZenBlock.php, если должен вызываться /home/www/sat/Sources/Class-ZenBlock.php
Файлы точно распаковываются в нужные директории? К примеру, директории Themes и Sources из архива с модом должны копироваться в корневую директорию форума, в которой уже должны находиться такие же директории. Тут либо проблема с путями (проверьте переменные $boarddir и $sourcedir в Settings.php), либо с правами на директории (файлы никуда не копируются при установке).

**Comment by satsis** [comment]
Файлы не распаковывает.
Т.е. после установки модуля файлов в каталогах нет. Так, почему-то только при установке ваших модулей.
```
$boarddir = __DIR__;
$sourcedir = __DIR__ . '/Sources';
```

**Comment by dragomano** [comment]
Тогда вручную распакуйте их куда надо. Также можно вручную добавить в базу данных информацию  о хуках, которые нужно запускать. Например, в случае с данным модом, смотрим строчку `<hook hook="integrate_pre_load" function="ZenBlock::hooks" file="$sourcedir/Class-ZenBlock.php" /> 
` в package-info.xml. Это означает, что надо в таблице settings создать или найти уже созданную строчку _integrate_pre_load_ и добавить туда строчку `$sourcedir/Class-ZenBlock.php|ZenBlock::hooks`. Если там уже есть записи других модов, поставьте перед добавляемой строчкой запятую. После этого обновить кэш в админке. Если файл Class-ZenBlock.php будет находиться по корректному пути (внутри Sources), появятся настройки мода в админке и все заработает.

**Comment by satsis** [comment]
Так тут вопрос почему именно ваши модули не копируют файлы в каталоге. Хотелось бы автоматизации. 
Другие модули копируют файлы, я список выше написал.
файл архива загружает в каталог Packages, но не создаёт каталог tmp внутри.
Права 
[root@bugs Packages]# chown -R :apache /home/www/sat/Packages/
[root@bugs Packages]# chmod -R g+rw /home/www/sat/Packages/

куда копать чтобы поставило? 

Если создать руками tmp, то нет ошибок при установке, но и файлы не копирует. Каталог tmp сразу удаляет.

**Comment by dragomano** [comment]
Там не tmp директория, а вроде temp должна создаваться и удаляться автоматически при каждой установке. Для пробы попробуйте создать ее вручную и поставить права 777. Также попробуйте поменять права через страницу Менеджер пакетов - Права доступа на файлы. На эту тему полно информации на simplemachines.ru.
Моды все разные, я не могу знать, почему одни ставятся, а другие нет.

**Comment by dragomano** [comment]
Установил последнюю Ubuntu на VirtualBox, поставил LAMP, права 777 на директорию /var/www/html, скопировал туда дистрибутив SMF, установил SMF. Затем установил Zen Block - все нормально, настройки отображаются, мод работает.

**Comment by satsis** [comment]
Каталог temp создаётся от пользователя ftp когда я загружаю ваш модуль
права на каталог /Packages есть у Apache
Форум работает, нигде ошибок нет
В логах только ошибки на ваши модули.
Скажите что мне проверить, я это сделаю.

**Comment by dragomano** [comment]
Я же объяснил, что проблема в правах, а не в модах. С Linux я мало знаком, советую поискать ответы на simplemachines.ru

**Comment by satsis** [comment]
Я же выше писал что только ваши моды не ставит. С другими проблем нет.

**Comment by dragomano** [comment]
> Ваши ставит без ошибок, но при удалении файлы не найдены

> Не смог ни один ваш модуль поставить

> куда копать чтобы поставило?

Либо вручную файлы копировать, либо с правами разбираться.
